const HOLESTOOTH_DEPTH: number = 5
const HOLESTOOTH_SUBDIVIDER: number = 3
const HOLESTOOTH_HOLD_OFF_TO_ENJOY_THE_EFFECT: number = 2

export {
	HOLESTOOTH_DEPTH,
	HOLESTOOTH_SUBDIVIDER,
	HOLESTOOTH_HOLD_OFF_TO_ENJOY_THE_EFFECT,
}
